export const ADD_PAINTINGS = 'ADD_PAINTINGS';
export const PAINTINGS_LOADING = 'PAINTINGS_LOADING';
export const PAINTINGS_FAILED = 'PAINTINGS_FAILED';

export const ADD_ACCESSORIES = 'ADD_ACCESSORIES';
export const ACCESSORIES_LOADING = 'ACCESSORIES_LOADING';
export const ACCESSORIES_FAILED = 'ACCESSORIES_FAILED';

export const ADD_JEWELLERY = 'ADD_JEWELLERY';
export const JEWELLERY_LOADING = 'JEWELLERY_LOADING';
export const JEWELLERY_FAILED = 'JEWELLERY_FAILED';

export const ADD_EVENTS = 'ADD_EVENTS';
export const EVENTS_LOADING = 'EVENTS_LOADING';
export const EVENTS_FAILED = 'EVENTS_FAILED';

export const ADD_DEALS = 'ADD_DEALS';
export const DEALS_LOADING = 'DEALS_LOADING';
export const DEALS_FAILED = 'DEALS_FAILED';

export const ADD_SELLS = 'ADD_SELLS';
export const SELLS_LOADING = 'SELLS_LOADING';
export const SELLS_FAILED = 'SELLS_FAILED';

export const ADD_FREES = 'ADD_FREES';
export const FREES_LOADING = 'FREES_LOADING';
export const FREES_FAILED = 'FREES_FAILED';

export const ADD_SERVICES = 'ADD_SERVICES';
export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_FAILED = 'SERVICES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const ADD_ARTISTS = 'ADD_ARTISTS';
export const ARTISTS_LOADING = 'ARTISTS_LOADING';
export const ARTISTS_FAILED = 'ARTISTS_FAILED';

export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';